### ISSUE TITLE
Add support for IMSI as unique identifier for a UE

### ISSUE THREAD

**Issue by shadansari** [onosproject/onos-ric#116]
Currently, we are using the CRNTI as the UE identifier. In a real network, the IMSI (or IMEI) is used to uniquely identify a UE or subscriber. This is especially needed once we fix https://github.com/onosproject/onos-ric/issues/115.

**Comment by SeanCondon** [comment]
Partially fixed by
https://github.com/onosproject/ran-simulator/pull/76
