### ISSUE TITLE
Change MLB app logic not to use telemetry but to use UE admission control

### ISSUE THREAD

**Issue by woojoong88** [onosproject/onos-ric#214]
Change MLB app logic not to use telemetry but to use UE admission control: Currently, MLB app leverages telemetry to check how many UEs are connected to each eNB. However, telemetry message is not suitable, because telemetry message for each UE is not always in the store especially when happening HO. 
When HO is triggered by HO app, both telemetry message and UE admission control message for a target UE are removed. The UE admission control message is updated in the HO procedure, whereas the telemetry message arrives when CQI value is changed. This means that the telemetry message for the UE may miss until CQI value is updated. As a result, the telemetry message for the UE is not always in the store. Therefore, I will change the MLB app to use UE admission control message, not to use telemetry message.

**Comment by shadansari** [comment]
@woojoong88 - do you plan to use the store for the UE admission control messages or would you be using the dispatcher (ie. similar to HO app)? I realize it can be done both ways but we may want to use the store so as to have one app that is using the store. Just

**Comment by shadansari** [comment]
a suggestion...

**Comment by woojoong88** [comment]
Yeah, right. And I am already working on MLB app to use a store, unlike HO app :D

**Comment by woojoong88** [comment]
Done.
