### ISSUE TITLE
E2 configuration

### ISSUE THREAD

**Issue by shadansari** [onosproject/onos-ric#247]
After the RIC connects to a new base-station over the E2 interface, it should push down configuration to the base station. The configuration is stored in onos-config and can be system-wide (common to all base stations) or per-base-station.

**Comment by SeanCondon** [comment]
The first step is to identify what might have to be configured and create a YANG model for it. This can then be created as a model plugin for `onos-config`

Secondly the `ran-simulator` can add a gNMI service on its E2 port and use this to configure the base station (cell)

**Comment by tomikazi** [comment]
As part of our feedback on E2 to O-RAN should be a recommendation to adopt gNMI as the industry standard. I have a feeling that this will be met with resistance by the established vendors because of the whole SCTP/ASN.1 silliness.

**Comment by SeanCondon** [comment]
As per the TST meeting on 6th May, the decision was made to have the ran-simulator support gNMI directly and `onos-config` would push config down directly to the cell. There is an E2Node model plugin for `onos-config` that models the E2Node
